

train_loader:
  modalities:
    S2L2A:
      before: /Users/evanleendertse/Documents/KSU/TerraMind/AgDamageModels/V1/Images/Before/S2L2A
      after: /Users/evanleendertse/Documents/KSU/TerraMind/AgDamageModels/V1/Images/After/S2L2A
    S1GRD:
      before: /Users/evanleendertse/Documents/KSU/TerraMind/AgDamageModels/V1/Images/Before/S1GRD
      after: /Users/evanleendertse/Documents/KSU/TerraMind/AgDamageModels/V1/Images/After/S1GRD
  label_dir: /Users/evanleendertse/Documents/KSU/TerraMind/AgDamageModels/V1/Images/Relabeled
  num_augmentations: 2
  patch_size: 224
  stride: 224
  add_random_offset: False
  preload: False # could double for both
  batch_size: 4
  shuffle: True
  num_workers: 2 #could double for both

validation_loader:
  modalities:
    S2L2A:
      before: /Users/evanleendertse/Documents/KSU/TerraMind/AgDamageModels/V1/Images/Before/S2L2A
      after: /Users/evanleendertse/Documents/KSU/TerraMind/AgDamageModels/V1/Images/After/S2L2A
    S1GRD:
      before: /Users/evanleendertse/Documents/KSU/TerraMind/AgDamageModels/V1/Images/Before/S1GRD
      after: /Users/evanleendertse/Documents/KSU/TerraMind/AgDamageModels/V1/Images/After/S1GRD
  label_dir: /Users/evanleendertse/Documents/KSU/TerraMind/AgDamageModels/V1/Images/Relabeled
  patch_size: 224
  stride: 224
  add_random_offset: False
  preload: False # could double for both
  batch_size: 4
  shuffle: True
  num_workers: 2 #could double for both

model:
  apply_weight_loss: False
  num_classes: 3
  ignore_index : 0
  positive_class: 2
  negative_class: 1
  TM_version: "terramind_v1_base"
  pretrained: True
  modalities: ["S2L2A", "S1GRD"]
  TM_finetune: False
  learning_rate: 0.0005
  num_epochs: 2
  seed: 22 

writer:
  experiment_name: "WriterTest"
  experiment_number: 1
