apply_weight_loss: False
weight_type: inverse # [inverse, pixels]
num_classes: 3
ignore_index : 0
positive_class: 2
negative_class: 1
TM_version: "terramind_v1_base"
pretrained: True
modalities: ["S2L2A", "S1GRD"]
TM_finetune: False
learning_rate: 0.0005
num_epochs: 2
seed: 22