modalities:
  S2L2A:
    before: Images_large/Validation/Before/S2L2A
    after: Images_large/Validation/After/S2L2A
  S1GRD:
    before: Images_large/Validation/Before/S1GRD/DESC
    after: Images_large/Validation/After/S1GRD/DESC
label_dir: Images_large/Validation/Labels
patch_size: 224
stride: 224
preload: False
batch_size: 4
shuffle: True
num_workers: 2