modalities:
  S2L2A:
    before: Images_small/Before/S2L2A
    after: Images_small/After/S2L2A
  S1GRD:
    before: Images_small/Before/S1GRD
    after: Images_small/After/S1GRD
label_dir: Images_small/Relabeled
num_augmentations: 2
patch_size: 224
stride: 224
preload: False
batch_size: 4
shuffle: True
num_workers: 2